server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: 15421542
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.wen: DEBUG
    org.hibernate: INFO
ead:
  api:
    url:
      course: 'http://localhost:8082'